# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false

language: python

cache:
    apt: true
    directories:
      - $HOME/.cache/pip
      - $HOME/.ccache

dist: trusty

virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6.2" COVERAGE="true" INSTALL_MKL="true"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" PANDAS_VERSION="0.20.3"
           CYTHON_VERSION="0.26.1" PYAMG_VERSION="3.3.2" PILLOW_VERSION="4.3.0"
           COVERAGE=true CHECK_PYTEST_SOFT_DEPENDENCY="true" TEST_DOCSTRINGS="true" RUN_FLAKE8="false"
    # - DISTRIB="ubuntu" PYTHON_VERSION="3.6" COVERAGE="true"
    # - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="false"
addons:
  apt:
    packages:
      - git
      - python-pip
      - python-pyaudio
      - python3-pyaudio
# before_install:
#   - sudo apt-get -qq update
# # matplotlib requires a backend (see matplotlibrc), tkagg is one option:
# #$ sudo apt-get install tcl-dev tk-dev python-tk python3-tk
#   - sudo apt-get install -y swig libpulse-dev libportaudio-dev python-pyaudio
#   - sudo apt install gfortran libopenblas-dev liblapack-dev python-scipy python-matplotlib python-numpy libpng12-dev libfreetype6-dev
#   # - sudo apt-get install -y pocketsphinx
install:
  - source tests/travis_install.sh
  # - pip install -r requirements.txt
before_script:
  - git config --global user.email "github@aira.io"
  - git config --global user.name "Aira"
script:
  - conda list
  - bash tests/run_tests.sh
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
