name: aichat
channels: !!python/tuple
  - menpo
  - defaults
  - conda-forge
  - akode
dependencies:
  - python=3.6
  - opencv
  - cffi
  - jasper
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pyqt
  - pytest
  - pytest-cov
  - portaudio
  - readline     
  - scipy
  - swig
  - speechrecognition
  - pip:
    - soundfile
    - regex
    - exrex
    - pyttsx3
    - pocketsphinx
    - tensorflow==1.2.0
    - paho-mqtt
    - scipy==1.0.0
    - sklearn
    - scikit-image
    - google-cloud-vision
    - vocabulary
    - pyaudio
